[project]
name = "web-shop-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Artem Ryazanov", email = "wemnts@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.20.0",
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.6",
    "sqlalchemy>=2.1.1",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
web-shop-fastapi = "web_shop_fastapi:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]
