[project]
name = "web-shop-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Artem Ryazanov", email = "wemnts@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "phonenumbers>=9.0.40",
    "psycopg[binary]>=3.3.6",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-extra-types>=2.11.1",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.1.1",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
web-shop-fastapi = "web_shop_fastapi:main"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]
