"""add role to users

Revision ID: 1b0014e0280f
Revises: 5f5a7053cb7a
Create Date: 2026-10-08 10:14:33.891444

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b0014e0280f"
down_revision: str | Sequence[str] | None = "5f5a7053cb7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum(
                "customer",
                "admin",
                name="user_role",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="customer",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
